### ISSUE TITLE
asadmin

### ISSUE THREAD

**Issue by joshskains** [realityforge/chef-glassfish#49]
So we noticed that when using this cookbook, the cookbook's use of asadmin for every action is brutal on performance. It takes forever. And does so every 5 minutes, even if there is nothing to do. Could we be doing something wrong, or is the asadmin command just too expensive?

**Comment by realityforge** [comment]
The asadmin command is essentially too slow if we use it in the way we have been using it. So more recent (unreleased) versions of the cookbook will load a "cache" of the properties in the server. Then rather than running asadmin to check if each each resource is present on the server, we just check the property cache. i.e. See https://github.com/realityforge/chef-glassfish/blob/master/providers/custom_resource.rb#L22

This approach dropped our configures from 700 seconds to 30 seconds for a no-change converge. However we are aiming to drop this down to 10-15 seconds with new approach we are using. The plan is to use caching more universally across the resources. We are doing this by rewriting the internals of the cookbook and writing a comprehensive test suite. You can see the progress at https://github.com/realityforge/redfish - the hope is to get this out in the 2-3 weeks.

**Comment by joshskains** [comment]
I appreciate the reply. Is there a version you'd recommend that would help us reduce some of the load times?

**Comment by realityforge** [comment]
The last release should reduce the load times significantly. 

And just starting to get back to looking at this after a break - Recently had my first child and only just starting to get some sleep again ;).
